version: 2

models:
  - name: walmart_date_dim
    description: "SCD1 Date dimension for Walmart sales"
    columns:
      - name: date_id
        description: "Surrogate key for each store-date-dept combination"
        tests:
          - unique
          - not_null
  - name: walmart_store_dim
    description: "Store dimension for Walmart data"
    columns:
      - name: store_id
        tests:
          - not_null
      - name: dept_id
        tests:
          - not_null